# -*- coding: utf-8 -*-
"""Copy of Synthetic Data Generation (Original).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yECVcAEH17TKlmm0UCb95q8qA0S77QEP
"""

from google.colab import drive
drive.mount('/content/drive')

# Clean any half-installed versions
!pip uninstall -y sdv copulas pingouin scipy

# Install a compatible combination
!pip install sdv==1.17.4 copulas==0.12.3 pingouin==0.5.4 scipy==1.12.0 rpy2==3.5.15

# Install R system
!apt-get update -qq
!apt-get install -y r-base

# Install binary CRAN `lavaan` and dependencies
!Rscript -e "install.packages(c('lavaan', 'psych'), repos='http://cran.rstudio.com/', dependencies=TRUE)"

# Load R packages once
import rpy2.robjects as ro
ro.r('library(lavaan); library(psych)')

import sdv, copulas, pingouin, scipy, rpy2
print("✅ sdv:", sdv.__version__,
      "| copulas:", copulas.__version__,
      "| pingouin:", pingouin.__version__,
      "| scipy:", scipy.__version__,
      "| rpy2:", rpy2.__version__)

import pandas as pd

# Assuming the files are in the root of 'My Drive'
student_df = pd.read_csv('/content/drive/My Drive/student_data_sample.csv')
school_df = pd.read_csv('/content/drive/My Drive/school_data_sample.csv')
school_metadata_df = pd.read_csv('/content/drive/My Drive/school_metadata.csv')

print('Student Data (first 5 rows):')
display(student_df.head())

print('\nSchool Data (first 5 rows):')
display(school_df.head())

print('\nSchool Metadata (first 5 rows):')
display(school_metadata_df.head())

import torch
print("CUDA available:", torch.cuda.is_available())
print("GPU device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU only")

import numpy as np

# Merge (student <- school)
merge_keys = ["CNT", "CNTSCHID"]
merged = student_df.merge(school_df, on=merge_keys, how="left")

# Variables used in the SEM model (same as your script)
model_vars = [
    "ST268Q01JA","ST268Q04JA","ST268Q07JA",
    "SC064Q01TA","SC064Q02TA","SC064Q03TA","SC064Q04NA","SC064Q05WA","SC064Q06WA",
    "PV1MATH","PV2MATH","PV3MATH","PV4MATH","PV5MATH","PV6MATH","PV7MATH","PV8MATH","PV9MATH","PV10MATH",
    "ST004D01T","MISCED","ESCS","ST001D01T","SCHSIZE"
]


# Recode gender and z-scores
merged["female"] = np.where(merged["ST004D01T"] == 1, 1, 0)
for v in ["ESCS", "ST001D01T", "SCHSIZE"]:
    merged[v + "_z"] = (merged[v] - merged[v].mean()) / merged[v].std()

# Do NOT drop rows with missing indicators — FIML will handle them
df_core = merged[model_vars + ["female","ESCS_z","ST001D01T_z","SCHSIZE_z"]]

print(df_core.shape, "rows, cols:", len(df_core.columns))

# Optional: Standardize continuous variables for SEM stability
# Comment out if studying raw scaling
numeric_cols = ["ESCS", "ST001D01T", "SCHSIZE"]
for col in numeric_cols:
    if col in df_core.columns:
        df_core[col] = (df_core[col] - df_core[col].mean()) / df_core[col].std()

# %%
import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
pandas2ri.activate()

LAVAAN = """
SMP =~ PV1MATH + PV2MATH + PV3MATH + PV4MATH + PV5MATH +
       PV6MATH + PV7MATH + PV8MATH + PV9MATH + PV10MATH
SMS =~ ST268Q01JA + ST268Q04JA + ST268Q07JA
SPI =~ SC064Q01TA + SC064Q02TA + SC064Q03TA + SC064Q04NA +
       SC064Q05WA + SC064Q06WA

SMS ~ a*SPI + c1*female + c2*ESCS_z + c3*ST001D01T + c4*MISCED + c5*SCHSIZE_z
SMP ~ b*SMS + cprime*SPI + d1*female + d2*ESCS_z + d3*ST001D01T + d4*MISCED + d5*SCHSIZE_z

indirect := a*b
total := cprime + (a*b)
"""

def fit_sem_return_artifacts(pdf):
    """
    Fits SEM in lavaan (R) via rpy2 and returns:
      - fm: dict of fit indices (CFI, TLI, RMSEA, SRMR, etc.)
      - std: lavaan parameterEstimates (standardised) as DataFrame
      - lat_cor_df: latent variable correlation matrix as DataFrame
      - rsq_df: R² per endogenous latent variable (like Table 5 in the paper)
    """

    import numpy as np, pandas as pd
    from rpy2 import robjects as ro
    from rpy2.robjects import pandas2ri

    pandas2ri.activate()

    # Convert pandas -> R
    with pandas2ri.converter.context():
        r_df = pandas2ri.py2rpy(pdf)

    ro.globalenv["pisa_dat"] = r_df
    ro.globalenv["model_string"] = LAVAAN

    ro.r('fit <- sem(model_string, data=pisa_dat, std.lv=TRUE, fixed.x=FALSE, missing="fiml")')

    # --- 1. Fit measures (global) ---
    ro.r('fm_df <- data.frame(metric=names(fitMeasures(fit)), '
          'value=as.numeric(fitMeasures(fit)))')
    fm_df = pandas2ri.rpy2py(ro.r('fm_df'))
    fm = dict(zip(fm_df["metric"], fm_df["value"]))

    # --- 2. Standardised parameter estimates ---
    std_sol = ro.r('parameterEstimates(fit, standardized=TRUE)')
    if hasattr(std_sol, "names"):
        std = pandas2ri.rpy2py(std_sol)
    else:
        std = pd.DataFrame(np.array(std_sol))

    # --- 3. Latent variable correlations ---
    lat_cor = ro.r('lavInspect(fit, "cor.lv")')
    if hasattr(lat_cor, "names"):
        lat_cor_df = pandas2ri.rpy2py(lat_cor)
    else:
        lat_cor_df = pd.DataFrame(np.array(lat_cor))

    try:
        lnames = list(ro.r('rownames(lavInspect(fit, "cor.lv"))'))
        lat_cor_df = pd.DataFrame(np.array(lat_cor_df), index=lnames, columns=lnames)
    except Exception:
        lat_cor_df = pd.DataFrame(np.array(lat_cor_df))

    # --- 4. R-squared for endogenous latents ---
    # Coerce to data.frame in R to avoid ndarray return
    ro.r('rsq_df <- as.data.frame(lavInspect(fit, "rsquare"))')
    rsq_df_r = ro.r('rsq_df')

    # Convert to Pandas
    rsq_py = pandas2ri.rpy2py(rsq_df_r)

    # Standardize column names
    if isinstance(rsq_py, pd.DataFrame):
        rsq_df = rsq_py.reset_index().rename(columns={'index': 'Latent', 0: 'R2'})
    else:
        rsq_df = pd.DataFrame([])

    # Warn on unexpected NA metrics
    if any(np.isnan(list(fm.values()))):
        print("⚠️ Warning: NaN values detected in SEM fit metrics. Model may be unstable.")

    return fm, std, lat_cor_df, rsq_df

# Fit on real data once here (you’ll reuse later)
real_fit, real_std, real_lat_cor, real_rsq = fit_sem_return_artifacts(df_core)
print("Real fit (selected):", {k: round(real_fit[k],3) for k in ["cfi","tli","rmsea","srmr","chisq","df"]})
real_loadings = (real_std[real_std['op']=='=~'][['lhs','rhs','std.all']]
                 .rename(columns={'lhs':'latent','rhs':'indicator','std.all':'loading'}))
display(real_loadings.head())
display(real_rsq)

# %%
import pandas as pd
import numpy as np
from pingouin import cronbach_alpha

# Tucker's Phi (congruence) per latent
def tucker_congruence(load_real, load_synth):
    merged = pd.merge(load_real, load_synth, on=['latent','indicator'], suffixes=('_real','_synth'))
    out = []
    for latent in merged['latent'].unique():
        sub = merged[merged['latent']==latent]
        num = np.sum(sub['loading_real'] * sub['loading_synth'])
        den = np.sqrt(np.sum(sub['loading_real']**2) * np.sum(sub['loading_synth']**2))
        out.append({'Construct': latent, 'Tucker_Congruence': np.round(num/den,3) if den else np.nan})
    return pd.DataFrame(out)

# Reliability (α, CR, AVE) – this matches the paper’s CR/AVE/alpha section
def reliability_table(std_solution, df_for_alpha):
    loads = std_solution[std_solution['op']=='=~'][['lhs','rhs','std.all']].copy()
    loads.columns = ['latent','indicator','loading']
    rows = []
    for latent in loads['latent'].unique():
        sub = loads[loads['latent']==latent]
        indicators = sub['indicator'].tolist()
        lam = sub['loading'].astype(float).values
        CR  = (lam.sum()**2) / ((lam.sum()**2) + np.sum(1 - lam**2))
        AVE = np.sum(lam**2) / len(lam)
        try:
            alpha, _ = cronbach_alpha(df_for_alpha[indicators].dropna())
        except Exception:
            alpha = np.nan
        rows.append(dict(
            Construct=latent,
            Cronbach_alpha=np.round(alpha,3),
            Composite_Reliability=np.round(CR,3),
            AVE=np.round(AVE,3)
        ))
    return pd.DataFrame(rows)

# Fornell–Larcker discriminant validity table:
# diagonal = sqrt(AVE); off-diagonal = latent correlations.
def fornell_larcker_table(reliab_df, lat_cor_df):
    rel = reliab_df.set_index("Construct")
    sqrt_ave = np.sqrt(rel["AVE"])

    # align order
    latents = list(sqrt_ave.index)
    corr = lat_cor_df.loc[latents, latents].copy()

    for l in latents:
        corr.loc[l, l] = sqrt_ave.loc[l]

    corr.index.name = "Latent"
    return corr

# Structural paths table (standardised coefficients + p-values)
def structural_paths_table(std_solution):
    paths = std_solution[std_solution['op']=="~"].copy()
    # Keep only latent DV/IVs if you want (here left generic)
    paths = paths[['lhs','rhs','est','se','pvalue','std.all']]
    paths = paths.rename(columns={
        'lhs': 'DV',
        'rhs': 'IV',
        'est': 'B_unstd',
        'std.all': 'B_std'
    })
    return paths

# %%
from sdv.metadata import Metadata
from sdv.single_table import GaussianCopulaSynthesizer

# Detect metadata automatically
metadata = Metadata.detect_from_dataframe(df_core)
metadata.save_to_json("pisa2022_metadata.json")

gc = GaussianCopulaSynthesizer(
    metadata,
    enforce_min_max_values=True
)
gc.fit(df_core)

synth = gc.sample(num_rows=len(df_core)).copy()

# --- Post-process ordinal/binary variables
def round_to_int(s, lo=None, hi=None):
    x = s.round().astype("Int64")
    if lo is not None:
        x = x.clip(lo, hi)
    return x.astype(float)

for col in [
    'ST268Q01JA','ST268Q04JA','ST268Q07JA',
    'SC064Q01TA','SC064Q02TA','SC064Q03TA',
    'SC064Q04NA','SC064Q05WA','SC064Q06WA'
]:
    if col in synth:
        synth[col] = round_to_int(synth[col], 1, 5)

if 'MISCED' in synth:
    synth['MISCED'] = round_to_int(synth['MISCED'], 0, 5)
if 'female' in synth:
    synth['female'] = round_to_int(synth['female'], 0, 1)

for v in ["ESCS","ST001D01T","SCHSIZE"]:
    if v in synth:
        synth[v + "_z"] = (synth[v] - synth[v].mean()) / synth[v].std()

print("✅ Synthetic (GaussianCopula) sample shape:", synth.shape)
display(synth.head())

# Optional: Report any columns dropped
dropped_cols = set(df_core.columns) - set(synth.columns)
if dropped_cols:
    print(f"⚠️ Dropped columns due to NaNs: {dropped_cols}")


# --- Fit SEM on synthetic data ---
synth_fit, synth_std, synth_lat_cor, synth_rsq = fit_sem_return_artifacts(synth)

# Loadings tables
synth_loadings = (synth_std[synth_std['op']=='=~'][['lhs','rhs','std.all']]
                  .rename(columns={'lhs':'latent','rhs':'indicator','std.all':'loading'}))

# Tucker congruence
congruence_df = tucker_congruence(real_loadings, synth_loadings)

# Reliability (α, CR, AVE)
real_reliab  = reliability_table(real_std,  df_core)
synth_reliab = reliability_table(synth_std, synth)

# Fornell–Larcker discriminant validity (like Table 4 in the paper)
real_fl  = fornell_larcker_table(real_reliab,  real_lat_cor)
synth_fl = fornell_larcker_table(synth_reliab, synth_lat_cor)

# Structural paths + p-values (like Table 5 in the paper)
real_paths  = structural_paths_table(real_std)
synth_paths = structural_paths_table(synth_std)

# --- Fit deltas (global fit) ---
sel = ["cfi","tli","rmsea","srmr","chisq","df"]
cmp = pd.DataFrame({
    "metric": sel,
    "real":   [real_fit.get(k, np.nan)  for k in sel],
    "synth":  [synth_fit.get(k, np.nan) for k in sel]
})
cmp["delta"] = cmp["synth"] - cmp["real"]

print("=== Global fit comparison (Real vs GaussianCopula) ===")
display(cmp.round(3))

print("\n=== Tucker congruence (Real vs GaussianCopula) ===")
display(congruence_df)

print("\n=== Real reliability (α, CR, AVE) ===")
display(real_reliab)

print("\n=== Synthetic reliability (α, CR, AVE) ===")
display(synth_reliab)

print("\n=== Real Fornell–Larcker table ===")
display(real_fl.round(3))

print("\n=== Synthetic Fornell–Larcker table ===")
display(synth_fl.round(3))

print("\n=== Real structural paths (B_std, pvalue) ===")
display(real_paths[['DV','IV','B_std','pvalue']].round(3))

print("\n=== Synthetic structural paths (B_std, pvalue) ===")
display(synth_paths[['DV','IV','B_std','pvalue']].round(3))

print("\n=== Real R² (lavaan rsquare) ===")
display(real_rsq)

print("\n=== Synthetic R² (lavaan rsquare) ===")
display(synth_rsq)

# --- Save CSVs like the paper’s tables ---
cmp.round(4).to_csv("SEM_fit_comparison_real_vs_gaussiancopula.csv", index=False)
congruence_df.to_csv("SEM_tucker_congruence_gaussiancopula.csv", index=False)
real_reliab.to_csv("SEM_reliability_real.csv", index=False)
synth_reliab.to_csv("SEM_reliability_gaussiancopula.csv", index=False)
real_fl.round(4).to_csv("SEM_fornell_larcker_real.csv")
synth_fl.round(4).to_csv("SEM_fornell_larcker_gaussiancopula.csv")
real_paths.to_csv("SEM_paths_real.csv", index=False)
synth_paths.to_csv("SEM_paths_gaussiancopula.csv", index=False)
real_rsq.to_csv("SEM_rsquare_real.csv", index=False)
synth_rsq.to_csv("SEM_rsquare_gaussiancopula.csv", index=False)

print("\n✅ Saved comparison tables & synthetic sample for GaussianCopula.")
synth.to_csv("synthetic_gaussiancopula_sample.csv", index=False)

# %%
from sdv.single_table import CTGANSynthesizer

metadata = Metadata.detect_from_dataframe(df_core)

ctgan = CTGANSynthesizer(
    metadata,
    enforce_min_max_values=True,
    epochs=300,
    batch_size=128,
    pac=1              # disables the pack assertion issues
)
ctgan.fit(df_core)

synth_ctgan = ctgan.sample(num_rows=len(df_core)).copy()

# === Impute NaNs post-sampling ===
synth_ctgan = synth_ctgan.fillna(synth_ctgan.median(numeric_only=True))

# === Fix zero-variance variables in ordinal items ===
for col in ["SC064Q02TA"]:
    if synth_ctgan[col].nunique() <= 1:
        print(f"⚠ Replacing constant column {col} with values from real data distribution")
        real_vals = df_core[col].dropna()
        if len(real_vals) > 0:
            synth_ctgan[col] = np.random.choice(real_vals, size=len(synth_ctgan))
        else:
            synth_ctgan[col] = np.random.randint(1, 6, size=len(synth_ctgan))  # fallback

# Impute any remaining NaNs
synth_ctgan = synth_ctgan.fillna(synth_ctgan.median(numeric_only=True))

# === Fix low-variance ordinal variables ===
for col in ['SC064Q02TA', 'SC064Q06WA']:
    if synth_ctgan[col].std() < 0.1:
        synth_ctgan[col] = synth_ctgan[col] + np.random.uniform(-0.3, 0.3, size=len(synth_ctgan[col]))
        synth_ctgan[col] = synth_ctgan[col].clip(1, 5)  # preserve ordinal bounds

# === Recompute z-scores ===
for v in ["ESCS", "ST001D01T", "SCHSIZE"]:
    synth_ctgan[v + "_z"] = (synth_ctgan[v] - synth_ctgan[v].mean()) / synth_ctgan[v].std()


# --- Post-process (round Likert + recompute z-scores) ---
def round_to_int(s, lo=None, hi=None):
    x = s.round().astype("Int64")
    if lo is not None:
        x = x.clip(lo, hi)
    return x.astype(float)

for col in [
    'ST268Q01JA','ST268Q04JA','ST268Q07JA',
    'SC064Q01TA','SC064Q02TA','SC064Q03TA',
    'SC064Q04NA','SC064Q05WA','SC064Q06WA'
]:
    if col in synth_ctgan:
        synth_ctgan[col] = round_to_int(synth_ctgan[col], 1, 5)

if 'MISCED' in synth_ctgan:
    synth_ctgan['MISCED'] = round_to_int(synth_ctgan['MISCED'], 0, 5)
if 'female' in synth_ctgan:
    synth_ctgan['female'] = round_to_int(synth_ctgan['female'], 0, 1)

for v in ["ESCS","ST001D01T","SCHSIZE"]:
    if v in synth_ctgan:
        synth_ctgan[v + "_z"] = (synth_ctgan[v] - synth_ctgan[v].mean()) / synth_ctgan[v].std()

print("✅ CTGAN synthetic sample:", synth_ctgan.shape)
display(synth_ctgan.head())

# --- Fit SEMs on all three datasets ---
real_fit, real_std, real_lat_cor, real_rsq   = fit_sem_return_artifacts(df_core)
gaus_fit, gaus_std, gaus_lat_cor, gaus_rsq   = fit_sem_return_artifacts(synth)
ctgan_fit, ctgan_std, ctgan_lat_cor, ctgan_rsq = fit_sem_return_artifacts(synth_ctgan)

def load_tbl(std_df):
    return (std_df[std_df['op']=='=~'][['lhs','rhs','std.all']]
            .rename(columns={'lhs':'latent','rhs':'indicator','std.all':'loading'}))

real_load = load_tbl(real_std)
gaus_load = load_tbl(gaus_std)
ctgan_load = load_tbl(ctgan_std)

# Tucker congruence
gaus_tucker  = tucker_congruence(real_load, gaus_load)
ctgan_tucker = tucker_congruence(real_load, ctgan_load)

# Reliability
real_rel  = reliability_table(real_std,  df_core)
gaus_rel  = reliability_table(gaus_std,  synth)
ctgan_rel = reliability_table(ctgan_std, synth_ctgan)

# Fornell–Larcker
real_fl   = fornell_larcker_table(real_rel,  real_lat_cor)
gaus_fl   = fornell_larcker_table(gaus_rel,  gaus_lat_cor)
ctgan_fl  = fornell_larcker_table(ctgan_rel, ctgan_lat_cor)

# Structural paths
real_paths   = structural_paths_table(real_std)
gaus_paths   = structural_paths_table(gaus_std)
ctgan_paths  = structural_paths_table(ctgan_std)

# --- Fit indices table ---
sel = ["cfi","tli","rmsea","srmr","chisq","df"]
cmp = pd.DataFrame({
    "metric":  sel,
    "Real":    [real_fit.get(k, np.nan)  for k in sel],
    "Gaussian":[gaus_fit.get(k, np.nan)  for k in sel],
    "CTGAN":   [ctgan_fit.get(k, np.nan) for k in sel]
})
cmp["Δ(CTGAN-Gauss)"] = cmp["CTGAN"] - cmp["Gaussian"]

print("=== SEM Global Fit Comparison (Real vs Gaussian vs CTGAN) ===")
display(cmp.round(3))

print("\n=== Tucker Congruence (Real vs Synthetic) ===")
tuckers = gaus_tucker.merge(ctgan_tucker, on='Construct', suffixes=('_Gauss','_CTGAN'))
display(tuckers)

print("\n=== Reliability & Validity (Cronbach α, CR, AVE) ===")
rel_merged = real_rel.merge(gaus_rel, on='Construct', suffixes=('_Real','_Gauss')) \
                     .merge(ctgan_rel, on='Construct', suffixes=('','_CTGAN'))
display(rel_merged)

print("\n=== Fornell–Larcker matrices ===")
print("\nReal:")
display(real_fl.round(3))
print("\nGaussian:")
display(gaus_fl.round(3))
print("\nCTGAN:")
display(ctgan_fl.round(3))

print("\n=== Structural paths (B_std, pvalue) – Real ===")
display(real_paths[['DV','IV','B_std','pvalue']].round(3))

print("\nCTGAN R²:")
display(ctgan_rsq)

# Save all CTGAN-related tables
cmp.round(4).to_csv("SEM_fit_comparison_real_gauss_ctgan.csv", index=False)
tuckers.to_csv("SEM_tucker_congruence_gauss_vs_ctgan.csv", index=False)
real_rel.to_csv("SEM_reliability_real.csv", index=False)
gaus_rel.to_csv("SEM_reliability_gaussian.csv", index=False)
ctgan_rel.to_csv("SEM_reliability_ctgan.csv", index=False)
real_fl.to_csv("SEM_fornell_larcker_real.csv")
gaus_fl.to_csv("SEM_fornell_larcker_gaussian.csv")
ctgan_fl.to_csv("SEM_fornell_larcker_ctgan.csv")
real_paths.to_csv("SEM_paths_real.csv", index=False)
gaus_paths.to_csv("SEM_paths_gaussian.csv", index=False)
ctgan_paths.to_csv("SEM_paths_ctgan.csv", index=False)
real_rsq.to_csv("SEM_rsquare_real.csv", index=False)
gaus_rsq.to_csv("SEM_rsquare_gaussian.csv", index=False)
ctgan_rsq.to_csv("SEM_rsquare_ctgan.csv", index=False)
synth_ctgan.to_csv("synthetic_ctgan_sample.csv", index=False)

print("\n✅ Saved CTGAN + Gaussian + Real metrics (CR, AVE, α, correlations, discriminant validity, paths, R²).")

